import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#eaf8fb",
	},
	scrollContent: {
		paddingHorizontal: 18,
		paddingTop: 16,
		paddingBottom: 22,
	},
	backgroundGlowTop: {
		position: "absolute",
		top: -90,
		right: -30,
		width: 210,
		height: 210,
		borderRadius: 105,
		backgroundColor: "rgba(18, 148, 136, 0.12)",
	},
	backgroundGlowBottom: {
		position: "absolute",
		bottom: 40,
		left: -50,
		width: 180,
		height: 180,
		borderRadius: 90,
		backgroundColor: "rgba(15, 118, 110, 0.08)",
	},
	heroCard: {
		borderRadius: 30,
		paddingHorizontal: 18,
		paddingTop: 14,
		paddingBottom: 16,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 12 },
		shadowOpacity: 0.2,
		shadowRadius: 18,
		elevation: 8,
	},
	headerRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		justifyContent: "space-between",
		gap: 12,
	},
	backButton: {
		width: 40,
		height: 40,
		borderRadius: 20,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "rgba(255,255,255,0.16)",
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.16)",
	},
	heroContent: {
		flex: 1,
	},
	title: {
		fontSize: 24,
		fontWeight: "800",
		color: "#ffffff",
		lineHeight: 28,
	},
	subtitle: {
		marginTop: 6,
		fontSize: 12,
		lineHeight: 18,
		color: "#d9fffb",
	},
	reportsContainer: {
		marginTop: 14,
		gap: 12,
	},
	reportCard: {
		borderRadius: 20,
		paddingHorizontal: 16,
		paddingVertical: 16,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 8 },
		shadowOpacity: 0.15,
		shadowRadius: 16,
		elevation: 5,
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.14)",
	},
	reportIconWrap: {
		width: 56,
		height: 56,
		borderRadius: 16,
		backgroundColor: "rgba(255,255,255,0.18)",
		alignItems: "center",
		justifyContent: "center",
		marginRight: 12,
	},
	reportInfo: {
		flex: 1,
	},
	reportTitle: {
		fontSize: 16,
		fontWeight: "800",
		color: "#ffffff",
		marginBottom: 4,
	},
	reportDescription: {
		fontSize: 12,
		color: "rgba(255,255,255,0.9)",
		lineHeight: 16,
		marginBottom: 8,
	},
	reportMeta: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
	},
	reportMetaText: {
		fontSize: 11,
		fontWeight: "700",
		color: "#fef3c7",
	},
	reportArrow: {
		marginLeft: 8,
	},
	infoCard: {
		marginTop: 16,
		backgroundColor: "#ffffff",
		borderRadius: 18,
		paddingHorizontal: 14,
		paddingVertical: 12,
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 12,
		borderWidth: 1,
		borderColor: "#d8eef1",
		shadowColor: "#164e63",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.08,
		shadowRadius: 10,
		elevation: 2,
	},
	infoContent: {
		flex: 1,
	},
	infoTitle: {
		fontSize: 14,
		fontWeight: "800",
		color: "#0f172a",
		marginBottom: 4,
	},
	infoText: {
		fontSize: 12,
		color: "#64748b",
		lineHeight: 16,
	},
});

export default styles;
