import { StyleSheet } from "react-native";

export default StyleSheet.create({
	container: {
		flex: 1,
		height: "100vh" as any,
		minHeight: "100%",
		backgroundColor: "#eef8fb",
		position: "relative",
		overflow: "hidden",
	},
	scrollView: {
		flex: 1,
		width: "100%",
		height: "100vh" as any,
		maxHeight: "100vh" as any,
		overflow: "scroll",
		overflowY: "auto",
		WebkitOverflowScrolling: "touch",
	} as any,
	backgroundGlowTop: {
		position: "absolute",
		top: -70,
		left: 0,
		right: 0,
		height: 190,
		backgroundColor: "rgba(14, 165, 233, 0.12)",
		zIndex: 0,
	},
	backgroundGlowBottom: {
		position: "absolute",
		bottom: -56,
		left: 0,
		right: 0,
		height: 160,
		backgroundColor: "rgba(20, 184, 166, 0.10)",
		zIndex: 0,
	},
	scrollContent: {
		flexGrow: 1,
		paddingTop: 10,
		paddingHorizontal: 8,
		paddingBottom: 22,
		width: "100%",
		maxWidth: 980,
		alignSelf: "center",
		gap: 10,
	},

	heroCard: {
		borderRadius: 18,
		padding: 10,
		overflow: "hidden",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.18)",
		elevation: 14,
		shadowColor: "#061826",
		shadowOffset: { width: 0, height: 16 },
		shadowOpacity: 0.28,
		shadowRadius: 24,
	},
	heroToolbar: {
		flexDirection: "row",
		alignItems: "flex-start",
		gap: 8,
		marginBottom: 8,
	},
	menuButton: {
		width: 28,
		height: 28,
		borderRadius: 14,
		backgroundColor: "rgba(255, 255, 255, 0.10)",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.20)",
		justifyContent: "center",
		alignItems: "center",
	},
	liveBadge: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		paddingHorizontal: 8,
		paddingVertical: 5,
		borderRadius: 999,
		backgroundColor: "rgba(8, 47, 73, 0.55)",
		borderWidth: 1,
		borderColor: "rgba(45, 212, 191, 0.30)",
	},
	liveDot: {
		width: 6,
		height: 6,
		borderRadius: 3,
		backgroundColor: "#20e68a",
	},
	liveBadgeText: {
		fontSize: 8,
		fontWeight: "900",
		color: "#dffcff",
	},
	dateCard: {
		marginLeft: "auto",
		minWidth: 92,
		borderRadius: 10,
		paddingVertical: 7,
		paddingHorizontal: 8,
		backgroundColor: "rgba(30, 64, 175, 0.28)",
		borderWidth: 1,
		borderColor: "rgba(125, 211, 252, 0.24)",
		gap: 5,
	},
	dateLine: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
	},
	dateText: {
		fontSize: 8,
		fontWeight: "900",
		color: "#ffffff",
	},
	heroMainRow: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 8,
		marginBottom: 10,
	},
	heroContent: {
		flex: 1,
		minWidth: 0,
	},
	title: {
		fontSize: 20,
		lineHeight: 23,
		fontWeight: "900",
		color: "#ffffff",
		textShadowColor: "rgba(0, 0, 0, 0.52)",
		textShadowOffset: { width: 0, height: 1 },
		textShadowRadius: 2,
	},
	subtitle: {
		marginTop: 7,
		fontSize: 8.8,
		lineHeight: 13,
		fontWeight: "800",
		color: "rgba(230, 250, 255, 0.90)",
		maxWidth: 205,
	},
	peopleScene: {
		width: 70,
		height: 72,
		position: "relative",
		alignItems: "center",
		justifyContent: "flex-end",
	},
	personBubble: {
		position: "absolute",
		width: 32,
		height: 32,
		borderRadius: 16,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.34)",
		elevation: 6,
		shadowColor: "#020617",
		shadowOffset: { width: 0, height: 8 },
		shadowOpacity: 0.22,
		shadowRadius: 10,
	},
	personBubbleBlue: {
		left: 0,
		top: 20,
		backgroundColor: "#2563eb",
	},
	personBubbleGreen: {
		right: 4,
		top: 12,
		backgroundColor: "#20c997",
	},
	personBubblePurple: {
		left: 23,
		top: 0,
		backgroundColor: "#7c3aed",
	},
	peopleBase: {
		width: 64,
		height: 18,
		borderRadius: 999,
		backgroundColor: "rgba(20, 184, 166, 0.64)",
	},

	statsGrid: {
		flexDirection: "row",
		gap: 6,
	},
	statCard: {
		flex: 1,
		minHeight: 88,
		backgroundColor: "#ffffff",
		borderRadius: 10,
		paddingVertical: 8,
		paddingHorizontal: 6,
		borderWidth: 1,
		borderColor: "rgba(226, 232, 240, 0.92)",
		position: "relative",
		overflow: "hidden",
		elevation: 6,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 8 },
		shadowOpacity: 0.10,
		shadowRadius: 12,
	},
	statIconWrap: {
		width: 25,
		height: 25,
		borderRadius: 13,
		justifyContent: "center",
		alignItems: "center",
		marginBottom: 5,
	},
	statLabel: {
		fontSize: 7.2,
		lineHeight: 9,
		fontWeight: "900",
		color: "#111827",
		minHeight: 18,
	},
	statValue: {
		fontSize: 17,
		lineHeight: 20,
		fontWeight: "900",
		color: "#0f172a",
		marginTop: 3,
		fontVariant: ["tabular-nums"],
	},
	statValueText: {
		fontSize: 10.5,
		lineHeight: 13,
	},
	statCaption: {
		fontSize: 6.8,
		lineHeight: 9,
		fontWeight: "800",
		color: "#7c8796",
		marginTop: 3,
		paddingBottom: 7,
	},
	statLoader: {
		marginTop: 6,
		marginBottom: 3,
		alignSelf: "flex-start",
	},
	statAccentLine: {
		position: "absolute",
		left: 7,
		right: 7,
		bottom: 6,
		height: 3,
		borderRadius: 999,
	},

	searchCard: {
		backgroundColor: "#ffffff",
		borderRadius: 12,
		padding: 10,
		borderWidth: 1,
		borderColor: "#e0edf4",
		elevation: 7,
		shadowColor: "#5f9aab",
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.12,
		shadowRadius: 14,
	},
	searchTitle: {
		fontSize: 11,
		fontWeight: "900",
		color: "#0f172a",
		marginBottom: 8,
	},
	inputShell: {
		height: 34,
		flexDirection: "row",
		alignItems: "center",
		gap: 7,
		backgroundColor: "#f8fbff",
		borderRadius: 9,
		borderWidth: 1,
		borderColor: "#d9e6f4",
		paddingHorizontal: 10,
		marginBottom: 8,
	},
	input: {
		flex: 1,
		height: "100%",
		paddingVertical: 0,
		fontSize: 10.5,
		fontWeight: "700",
		color: "#0f172a",
	},
	actionRow: {
		flexDirection: "row",
		gap: 7,
		marginBottom: 8,
	},
	actionButton: {
		flex: 1,
		minWidth: 0,
		borderRadius: 8,
		overflow: "hidden",
		elevation: 4,
		shadowColor: "#334155",
		shadowOffset: { width: 0, height: 5 },
		shadowOpacity: 0.15,
		shadowRadius: 8,
	},
	actionFill: {
		height: 31,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 4,
		paddingHorizontal: 5,
	},
	actionTextLight: {
		fontSize: 8.5,
		fontWeight: "900",
		color: "#ffffff",
	},
	buttonDisabled: {
		opacity: 0.48,
	},
	contentCard: {
		backgroundColor: "#ffffff",
		borderRadius: 12,
		padding: 9,
		borderWidth: 1,
		borderColor: "#dfeaf3",
		elevation: 7,
		shadowColor: "#5f9aab",
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.12,
		shadowRadius: 14,
	},
	contentTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		marginBottom: 8,
	},
	contentTitle: {
		fontSize: 12.5,
		fontWeight: "900",
		color: "#0f172a",
	},
	loader: {
		marginVertical: 28,
	},
	messageBox: {
		backgroundColor: "#fef3c7",
		borderLeftWidth: 4,
		borderLeftColor: "#f59e0b",
		paddingVertical: 10,
		paddingHorizontal: 12,
		borderRadius: 8,
		marginBottom: 10,
	},
	messageText: {
		fontSize: 11,
		fontWeight: "700",
		color: "#92400e",
		lineHeight: 16,
	},
	resultCounter: {
		fontSize: 9,
		fontWeight: "900",
		color: "#2563eb",
		marginBottom: 8,
		letterSpacing: 0,
		backgroundColor: "#eff6ff",
		borderWidth: 1,
		borderColor: "#bfdbfe",
		borderRadius: 9,
		paddingHorizontal: 10,
		paddingVertical: 7,
	},
	emptyState: {
		alignItems: "center",
		paddingVertical: 34,
	},
	emptyIconWrap: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: "#dcfce7",
		justifyContent: "center",
		alignItems: "center",
		marginBottom: 10,
	},
	emptyTitle: {
		fontSize: 14,
		fontWeight: "900",
		color: "#0f172a",
		marginBottom: 5,
	},
	emptyText: {
		fontSize: 11,
		fontWeight: "700",
		color: "#64748b",
		textAlign: "center",
		lineHeight: 16,
	},

	tableWrapper: {
		borderRadius: 10,
		overflow: "hidden",
		backgroundColor: "#f8fbff",
		borderWidth: 1,
		borderColor: "#d9e6f0",
	},
	tableHeaderRow: {
		flexDirection: "row",
		minHeight: 32,
		paddingHorizontal: 3,
		alignItems: "center",
	},
	tableHeaderCell: {
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 2,
	},
	tableActionHeaderCell: {
		width: 34,
		justifyContent: "center",
		alignItems: "center",
	},
	tableHeaderText: {
		fontSize: 6.8,
		fontWeight: "900",
		color: "#ffffff",
		textAlign: "center",
	},
	tableDataRow: {
		flexDirection: "row",
		minHeight: 43,
		marginHorizontal: 4,
		marginTop: 5,
		paddingHorizontal: 3,
		borderRadius: 9,
		alignItems: "center",
		borderWidth: 1,
		borderColor: "#e6eef5",
	},
	tableRowEven: {
		backgroundColor: "#ffffff",
	},
	tableRowOdd: {
		backgroundColor: "#f7fcff",
	},
	tableDataCell: {
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 1,
		minWidth: 0,
	},
	tableIconText: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 2,
		minWidth: 0,
	},
	tableDataText: {
		fontSize: 6.8,
		lineHeight: 8.5,
		fontWeight: "900",
		color: "#102033",
		textAlign: "center",
	},
	tableDataTextTight: {
		fontSize: 6.5,
		letterSpacing: 0,
	},
	tableActionCell: {
		width: 34,
		justifyContent: "center",
		alignItems: "center",
	},
	estadoBadge: {
		minWidth: 36,
		paddingVertical: 3,
		paddingHorizontal: 4,
		borderRadius: 999,
		justifyContent: "center",
		alignItems: "center",
	},
	estadoBadgeActivo: {
		backgroundColor: "#ecfdf3",
		borderWidth: 1,
		borderColor: "#8ceec6",
	},
	estadoBadgeInactivo: {
		backgroundColor: "#fff1f2",
		borderWidth: 1,
		borderColor: "#fda4af",
	},
	estadoBadgeText: {
		fontSize: 6.8,
		fontWeight: "900",
	},
	estadoBadgeTextActivo: {
		color: "#047857",
	},
	estadoBadgeTextInactivo: {
		color: "#be123c",
	},
	verButton: {
		width: 24,
		height: 24,
		borderRadius: 12,
		backgroundColor: "#eafff4",
		borderWidth: 1,
		borderColor: "#a7f3d0",
		justifyContent: "center",
		alignItems: "center",
	},
});
