import { StyleSheet } from "react-native";
import reporteBaseStyles from "./ReporteClientesStyles";

// ATAMAINE: Cobranzas adopta el sistema compacto de los reportes nuevos y
// mantiene estilos propios para autocompletados y filtros administrativos.
export const reporteCobranzasStyles = StyleSheet.create({
	...reporteBaseStyles,
	fieldLabel: {
		fontSize: 9,
		fontWeight: "900",
		color: "#334155",
		marginBottom: 6,
	},
        selectorWrap: {
                position: "relative",
                zIndex: 20,
                marginBottom: 8,
        },
        dniSelectorWrap: {
                zIndex: 40,
        },
	selectorShell: {
		minHeight: 42,
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingLeft: 11,
		paddingRight: 5,
		backgroundColor: "#f8fbff",
		borderRadius: 11,
		borderWidth: 1,
		borderColor: "#cfe0ef",
	},
	selectorShellFocused: {
		borderColor: "#14b8a6",
		backgroundColor: "#f4fffd",
	},
	selectorInput: {
		flex: 1,
		minWidth: 0,
		height: 40,
		paddingVertical: 0,
		fontSize: 10.5,
		fontWeight: "800",
		color: "#0f172a",
	},
	selectorIconButton: {
		width: 31,
		height: 31,
		borderRadius: 9,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#e8f8f5",
	},
	selectorClearButton: {
		width: 25,
		height: 31,
		alignItems: "center",
		justifyContent: "center",
	},
	optionsBox: {
		marginTop: 6,
		maxHeight: 230,
		backgroundColor: "#ffffff",
		borderWidth: 1,
		borderColor: "#bfe3df",
		borderRadius: 12,
		overflow: "hidden",
		elevation: 12,
		shadowColor: "#0f766e",
		shadowOffset: { width: 0, height: 9 },
		shadowOpacity: 0.18,
		shadowRadius: 14,
	},
	optionsHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 11,
		paddingVertical: 7,
		backgroundColor: "#ecfdf8",
		borderBottomWidth: 1,
		borderBottomColor: "#d7f1eb",
	},
	optionsHeaderText: {
		fontSize: 8,
		fontWeight: "900",
		color: "#0f766e",
		textTransform: "uppercase",
		letterSpacing: 0.35,
	},
	optionsScroll: {
		maxHeight: 190,
	},
	optionItem: {
		minHeight: 48,
		flexDirection: "row",
		alignItems: "center",
		gap: 9,
		paddingHorizontal: 10,
		paddingVertical: 8,
		borderBottomWidth: 1,
		borderBottomColor: "#edf3f7",
	},
	optionItemActive: {
		backgroundColor: "#effcf8",
	},
	optionIcon: {
		width: 30,
		height: 30,
		borderRadius: 9,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#e7f8f4",
	},
	optionContent: {
		flex: 1,
		minWidth: 0,
	},
	optionTitle: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "900",
		color: "#102033",
	},
	optionMeta: {
		marginTop: 3,
		fontSize: 8,
		fontWeight: "700",
		color: "#64748b",
	},
	optionEmpty: {
		alignItems: "center",
		paddingHorizontal: 14,
		paddingVertical: 17,
		gap: 5,
	},
        optionEmptyText: {
		fontSize: 9,
		fontWeight: "800",
		color: "#64748b",
                textAlign: "center",
        },
        dniSelectedCard: {
                flexDirection: "row",
                alignItems: "center",
                gap: 9,
                paddingHorizontal: 10,
                paddingVertical: 9,
                marginTop: -2,
                marginBottom: 9,
                backgroundColor: "#ecfdf8",
                borderWidth: 1,
                borderColor: "#a7eadc",
                borderRadius: 12,
        },
        dniSelectedIcon: {
                width: 32,
                height: 32,
                borderRadius: 10,
                alignItems: "center",
                justifyContent: "center",
                backgroundColor: "#0f9f8f",
        },
        dniSelectedCopy: {
                flex: 1,
                minWidth: 0,
        },
        dniSelectedLabel: {
                fontSize: 7.5,
                fontWeight: "900",
                color: "#0f766e",
                letterSpacing: 0.55,
        },
        dniSelectedName: {
                marginTop: 1,
                fontSize: 10.5,
                fontWeight: "900",
                color: "#0f172a",
        },
        dniSelectedMeta: {
                marginTop: 2,
                fontSize: 7.8,
                fontWeight: "700",
                color: "#52716d",
        },
	filterInputShell: {
		marginBottom: 8,
	},
	dateRow: {
		flexDirection: "row",
		gap: 7,
	},
	dateColumn: {
		flex: 1,
		minWidth: 0,
	},
});

export default reporteCobranzasStyles;
