import { StyleSheet } from "react-native";

export default StyleSheet.create({
	container: {
		flex: 1,
		height: "100vh" as any,
		minHeight: "100%",
		backgroundColor: "#eaf8fb",
		position: "relative",
		overflow: "hidden",
	},
	// ATAMAINE: En web el ScrollView necesita altura real para permitir bajar hasta toda la tabla.
	scrollView: {
		flex: 1,
		width: "100%",
		height: "100vh" as any,
		maxHeight: "100vh" as any,
		overflow: "scroll",
		overflowY: "auto",
		WebkitOverflowScrolling: "touch",
	} as any,
	backgroundGlowTop: {
		position: "absolute",
		top: -90,
		left: -120,
		width: 360,
		height: 360,
		backgroundColor: "rgba(10, 148, 136, 0.12)",
		borderRadius: 180,
		zIndex: 0,
	},
	backgroundGlowBottom: {
		position: "absolute",
		bottom: -100,
		right: -130,
		width: 340,
		height: 340,
		backgroundColor: "rgba(21, 101, 192, 0.08)",
		borderRadius: 170,
		zIndex: 0,
	},
	scrollContent: {
		flexGrow: 1,
		paddingTop: 14,
		paddingHorizontal: 12,
		paddingBottom: 24,
		width: "100%",
		maxWidth: 980,
		alignSelf: "center",
	},

	heroCard: {
		borderRadius: 24,
		padding: 17,
		marginBottom: 18,
		overflow: "hidden",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.20)",
		elevation: 14,
		shadowColor: "#082f49",
		shadowOffset: { width: 0, height: 18 },
		shadowOpacity: 0.26,
		shadowRadius: 22,
	},
	headerRow: {
		flexDirection: "row",
		alignItems: "flex-start",
		marginBottom: 16,
		gap: 12,
	},
	// ATAMAINE: El touch externo separa la interaccion del brillo interno del boton volver.
	backButtonTouch: {
		width: 48,
		height: 48,
		borderRadius: 24,
	},
	backButton: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: "rgba(255, 255, 255, 0.18)",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.26)",
		elevation: 5,
		shadowColor: "#062f3f",
		shadowOffset: { width: 0, height: 7 },
		shadowOpacity: 0.22,
		shadowRadius: 10,
	},
	heroContent: {
		flex: 1,
	},
	liveBadge: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		marginBottom: 10,
		alignSelf: "flex-start",
		paddingHorizontal: 11,
		paddingVertical: 6,
		backgroundColor: "rgba(255, 255, 255, 0.18)",
		borderRadius: 999,
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.20)",
	},
	liveDot: {
		width: 10,
		height: 10,
		borderRadius: 5,
		backgroundColor: "#22e06f",
	},
	liveBadgeText: {
		fontSize: 11,
		fontWeight: "800",
		color: "#f2fffb",
	},
	title: {
		fontSize: 23,
		fontWeight: "900",
		color: "#ffffff",
		lineHeight: 26,
		marginBottom: 2,
	},
	subtitle: {
		fontSize: 13,
		fontWeight: "700",
		color: "rgba(239, 253, 255, 0.84)",
		marginTop: 9,
		lineHeight: 18,
	},

	statsRow: {
		flexDirection: "row",
		gap: 10,
		justifyContent: "space-between",
	},
	statCard: {
		flex: 1,
		minHeight: 84,
		backgroundColor: "rgba(255, 255, 255, 0.14)",
		borderRadius: 18,
		padding: 12,
		borderWidth: 1,
		borderColor: "rgba(255, 255, 255, 0.22)",
		justifyContent: "center",
	},
	statLabel: {
		fontSize: 11,
		fontWeight: "900",
		color: "#ffffff",
		marginBottom: 5,
	},
	statValue: {
		fontSize: 31,
		fontWeight: "900",
		color: "#ffffff",
		marginBottom: 4,
	},
	statValueSmall: {
		fontSize: 16,
		fontWeight: "900",
		color: "#ffffff",
		marginBottom: 5,
	},
	statCaption: {
		fontSize: 11,
		fontWeight: "700",
		color: "rgba(239, 253, 255, 0.74)",
	},

	searchCard: {
		backgroundColor: "#ffffff",
		borderRadius: 22,
		padding: 15,
		marginBottom: 18,
		borderWidth: 1,
		borderColor: "#dff1f4",
		elevation: 9,
		shadowColor: "#4c8e9a",
		shadowOffset: { width: 0, height: 12 },
		shadowOpacity: 0.18,
		shadowRadius: 18,
	},
	searchTitle: {
		fontSize: 20,
		fontWeight: "900",
		color: "#111827",
		marginBottom: 18,
	},
	fieldLabel: {
		fontSize: 13,
		fontWeight: "900",
		color: "#111827",
		marginBottom: 10,
	},
	input: {
		borderWidth: 1,
		borderColor: "#bee9ec",
		borderRadius: 18,
		paddingHorizontal: 16,
		paddingVertical: 12,
		fontSize: 14,
		color: "#0f172a",
		marginBottom: 16,
		backgroundColor: "#f1fbfd",
		fontWeight: "500",
	},

	actionRow: {
		flexDirection: "row",
		gap: 7,
		marginBottom: 10,
		justifyContent: "space-between",
	},
	actionRowSecondary: {
		flexDirection: "column",
		gap: 10,
		justifyContent: "flex-start",
	},

	primaryAction: {
		flex: 1,
	},
	secondaryAction: {
		width: "100%",
		alignSelf: "stretch",
	},
	newAction: {
		flex: 1,
	},
	clearAction: {
		flex: 1,
	},
	buttonDisabled: {
		opacity: 0.5,
	},
	actionSurface: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 6,
		minHeight: 60,
		paddingVertical: 9,
		paddingHorizontal: 5,
		borderRadius: 18,
		borderWidth: 1,
		borderLeftWidth: 6,
		elevation: 4,
		shadowColor: "#64748b",
		shadowOffset: { width: 0, height: 7 },
		shadowOpacity: 0.16,
		shadowRadius: 10,
	},
	// ATAMAINE: Los bordes conservan la identidad de color y el gradiente vive en el componente.
	primaryActionSurface: {
		borderColor: "#2d6cdf",
	},
	secondaryActionSurface: {
		borderColor: "#f6a315",
		justifyContent: "flex-start",
		paddingHorizontal: 18,
	},
	newActionSurface: {
		borderColor: "#0f8f83",
	},
	clearActionSurface: {
		borderColor: "#607086",
	},

	actionIconBadge: {
		width: 38,
		height: 38,
		borderRadius: 13,
		justifyContent: "center",
		alignItems: "center",
	},
	primaryActionBadge: {
		backgroundColor: "rgba(37, 99, 235, 0.15)",
	},
	secondaryActionBadge: {
		backgroundColor: "rgba(245, 158, 11, 0.15)",
	},
	newActionBadge: {
		backgroundColor: "rgba(16, 185, 129, 0.15)",
	},
	clearActionBadge: {
		backgroundColor: "rgba(100, 116, 139, 0.15)",
	},

	primaryActionText: {
		fontSize: 12,
		fontWeight: "800",
		color: "#1f4fa8",
	},
	secondaryActionText: {
		fontSize: 15,
		fontWeight: "800",
		color: "#8a5215",
		textAlign: "center",
	},
	newActionText: {
		fontSize: 12,
		fontWeight: "800",
		color: "#116f65",
	},
	clearActionText: {
		fontSize: 12,
		fontWeight: "800",
		color: "#475569",
	},

	contentCard: {
		backgroundColor: "#ffffff",
		borderRadius: 22,
		padding: 9,
		borderWidth: 1,
		borderColor: "#dff1f4",
		elevation: 9,
		shadowColor: "#4c8e9a",
		shadowOffset: { width: 0, height: 12 },
		shadowOpacity: 0.18,
		shadowRadius: 18,
	},
	contentTitle: {
		fontSize: 22,
		fontWeight: "900",
		color: "#111827",
		marginBottom: 16,
	},

	loader: {
		marginVertical: 40,
	},

	messageBox: {
		backgroundColor: "#fef3c7",
		borderLeftWidth: 4,
		borderLeftColor: "#f59e0b",
		paddingVertical: 12,
		paddingHorizontal: 14,
		borderRadius: 8,
		marginBottom: 12,
	},
	messageText: {
		fontSize: 13,
		fontWeight: "500",
		color: "#92400e",
		lineHeight: 18,
	},

	resultCounter: {
		fontSize: 11,
		fontWeight: "900",
		color: "#0f766e",
		marginBottom: 12,
		letterSpacing: 0.2,
		textTransform: "uppercase",
		backgroundColor: "#ecfdf3",
		borderWidth: 1,
		borderColor: "#bbf7d0",
		borderRadius: 12,
		paddingHorizontal: 12,
		paddingVertical: 9,
	},

	emptyState: {
		alignItems: "center",
		paddingVertical: 40,
	},
	emptyIconWrap: {
		width: 56,
		height: 56,
		borderRadius: 28,
		backgroundColor: "#ccfbf1",
		justifyContent: "center",
		alignItems: "center",
		marginBottom: 12,
	},
	emptyTitle: {
		fontSize: 15,
		fontWeight: "700",
		color: "#0f172a",
		marginBottom: 6,
	},
	emptyText: {
		fontSize: 13,
		fontWeight: "500",
		color: "#64748b",
		textAlign: "center",
		lineHeight: 18,
	},

	tableWrapper: {
		borderWidth: 1,
		borderColor: "#d8e8ed",
		borderRadius: 20,
		overflow: "hidden",
		backgroundColor: "#ffffff",
		elevation: 2,
		shadowColor: "#8bbbc4",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.12,
		shadowRadius: 10,
	},
	tableTopAccent: {
		height: 6,
		backgroundColor: "#0f766e",
	},
	tableHeaderRow: {
		flexDirection: "row",
		backgroundColor: "#2353d8",
		minHeight: 50,
		paddingVertical: 9,
		paddingHorizontal: 2,
		alignItems: "center",
	},
	tableHeaderCell: {
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 2,
	},
	tableActionHeaderCell: {
		width: 50,
		justifyContent: "center",
		alignItems: "center",
	},
	tableHeaderText: {
		fontSize: 8.5,
		fontWeight: "800",
		color: "#ffffff",
		textAlign: "center",
	},

	// ATAMAINE: Filas mas bajas para que el listado respire menos y quepan mas registros.
	tableDataRow: {
		flexDirection: "row",
		minHeight: 66,
		paddingVertical: 8,
		paddingHorizontal: 2,
		borderBottomWidth: 1,
		borderBottomColor: "#dce9ee",
		alignItems: "center",
	},
	tableRowEven: {
		backgroundColor: "#ffffff",
	},
	tableRowOdd: {
		backgroundColor: "#f1fbfd",
	},
	tableRowMatch: {
		backgroundColor: "#e6f7ff",
		borderLeftWidth: 4,
		borderLeftColor: "#0f5bd4",
	},
	tableRowDim: {
		opacity: 0.6,
	},
	tableDataCell: {
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 2,
	},
	tableDataText: {
		fontSize: 9.2,
		fontWeight: "800",
		color: "#111827",
		textAlign: "center",
		lineHeight: 12,
	},
	tableDataTextTight: {
		fontSize: 8.8,
		letterSpacing: 0,
	},
	tableActionCell: {
		width: 50,
		justifyContent: "center",
		alignItems: "center",
	},

	estadoBadge: {
		minWidth: 48,
		paddingVertical: 6,
		paddingHorizontal: 5,
		borderRadius: 999,
		justifyContent: "center",
		alignItems: "center",
	},
	estadoBadgeActivo: {
		backgroundColor: "#ecfdf3",
		borderWidth: 1,
		borderColor: "#86efac",
	},
	estadoBadgeInactivo: {
		backgroundColor: "#fff1f2",
		borderWidth: 1,
		borderColor: "#fda4af",
	},
	estadoBadgeText: {
		fontSize: 8.5,
		fontWeight: "900",
	},
	estadoBadgeTextActivo: {
		color: "#15803d",
	},
	estadoBadgeTextInactivo: {
		color: "#be123c",
	},

	verButton: {
		minWidth: 40,
		minHeight: 36,
		paddingVertical: 7,
		paddingHorizontal: 8,
		backgroundColor: "#0d7b70",
		borderRadius: 12,
		borderWidth: 1,
		borderColor: "#066259",
		justifyContent: "center",
		alignItems: "center",
	},
	verButtonText: {
		fontSize: 10,
		fontWeight: "800",
		color: "#ffffff",
	},
});
