import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#eaf8fb",
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 22,
  },
  backgroundGlowTop: {
    position: "absolute",
    top: -90,
    right: -30,
    width: 210,
    height: 210,
    borderRadius: 105,
    backgroundColor: "rgba(18, 148, 136, 0.12)",
  },
  backgroundGlowBottom: {
    position: "absolute",
    bottom: 40,
    left: -50,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: "rgba(15, 118, 110, 0.08)",
  },
  heroCard: {
    borderRadius: 30,
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 16,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 8,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
  },
  heroContent: {
    flex: 1,
    marginLeft: 12,
  },
  liveBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    marginBottom: 8,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#22c55e",
    marginRight: 7,
  },
  liveBadgeText: {
    color: "#eafffb",
    fontSize: 10,
    fontWeight: "800",
  },
  title: {
    fontSize: 18,
    fontWeight: "800",
    color: "#ffffff",
    lineHeight: 22,
  },
  subtitle: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: "#d9fffb",
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 2,
  },
  statCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  statLabel: {
    color: "#d8fffb",
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 4,
  },
  statValue: {
    color: "#ffffff",
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 31,
  },
  statCaption: {
    color: "#c5f7f2",
    fontSize: 11,
    marginTop: 2,
  },
  statValueSmall: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 20,
  },
  searchCard: {
    marginTop: 10,
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 16,
    shadowColor: "#164e63",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#d8eef1",
  },
  searchTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#effbfc",
    borderWidth: 1,
    borderColor: "#c5e7eb",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#0f172a",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  actionRowSecondary: {
    flexDirection: "row",
    marginTop: 10,
  },
  primaryAction: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  newAction: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  clearAction: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  secondaryAction: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  // ATAMAINE: Superficie base para botones tipo tarjeta blanca con acento de color, como en dashboard.
  actionSurface: {
    minHeight: 48,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e6edf2",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 12,
    gap: 10,
    shadowColor: "#164e63",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  primaryActionSurface: {
    borderLeftWidth: 4,
    borderLeftColor: "#2563eb",
  },
  newActionSurface: {
    borderLeftWidth: 4,
    borderLeftColor: "#0f766e",
  },
  clearActionSurface: {
    borderLeftWidth: 4,
    borderLeftColor: "#64748b",
  },
  secondaryActionSurface: {
    borderLeftWidth: 4,
    borderLeftColor: "#f59e0b",
  },
  actionIconBadge: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryActionBadge: {
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  newActionBadge: {
    backgroundColor: "rgba(15, 118, 110, 0.12)",
  },
  clearActionBadge: {
    backgroundColor: "rgba(100, 116, 139, 0.14)",
  },
  secondaryActionBadge: {
    backgroundColor: "rgba(245, 158, 11, 0.14)",
  },
  primaryActionText: {
    color: "#1e3a8a",
    fontSize: 14,
    fontWeight: "800",
  },
  newActionText: {
    color: "#115e59",
    fontSize: 14,
    fontWeight: "800",
  },
  clearActionText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryActionText: {
    color: "#b45309",
    fontSize: 14,
    fontWeight: "800",
  },
  actionGradient: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 12,
  },
  actionText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  contentCard: {
    marginTop: 10,
    backgroundColor: "#ffffff",
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 14,
    shadowColor: "#164e63",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: "#d8eef1",
  },
  contentTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 10,
    paddingHorizontal: 6,
  },
  loader: {
    marginTop: 14,
    marginBottom: 10,
  },
  messageBox: {
    marginHorizontal: 6,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#fff4f4",
    borderWidth: 1,
    borderColor: "#ffd6d6",
  },
  messageText: {
    color: "#b91c1c",
    fontSize: 13,
    fontWeight: "600",
  },
  resultCounter: {
    marginTop: 6,
    marginBottom: 10,
    paddingHorizontal: 6,
    color: "#475569",
    fontSize: 13,
    fontWeight: "700",
  },
  tableWrapper: {
    width: "100%",
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#d7e8ee",
    backgroundColor: "#ffffff",
    shadowColor: "#1e3a8a",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  tableTopAccent: {
    height: 5,
    backgroundColor: "#0f766e",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#1d4ed8",
  },
  tableHeaderCell: {
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.18)",
    justifyContent: "center",
  },
  tableActionHeaderCell: {
    width: 56,
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderRightWidth: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  tableHeaderText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
  },
  tableDataRow: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#e1edf2",
    alignItems: "stretch",
  },
  tableRowEven: {
    backgroundColor: "#fcfeff",
  },
  tableRowOdd: {
    backgroundColor: "#f4fbff",
  },
  tableDataCell: {
    minHeight: 52,
    paddingVertical: 10,
    paddingHorizontal: 6,
    justifyContent: "center",
    borderRightWidth: 1,
    borderRightColor: "#e1edf2",
  },
  tableActionCell: {
    width: 56,
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  tableDataText: {
    fontSize: 10,
    color: "#0f172a",
    fontWeight: "600",
    textAlign: "center",
  },
  estadoBadge: {
    alignSelf: "center",
    minWidth: 48,
    borderRadius: 999,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderWidth: 1,
  },
  estadoBadgeActivo: {
    backgroundColor: "#ecfdf3",
    borderColor: "#86efac",
  },
  estadoBadgeInactivo: {
    backgroundColor: "#fff1f2",
    borderColor: "#fda4af",
  },
  estadoBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    textAlign: "center",
  },
  estadoBadgeTextActivo: {
    color: "#15803d",
  },
  estadoBadgeTextInactivo: {
    color: "#be123c",
  },
  verButton: {
    minWidth: 38,
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 8,
    backgroundColor: "#0f766e",
    borderWidth: 1,
    borderColor: "#115e59",
    alignItems: "center",
    justifyContent: "center",
  },
  verButtonText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "800",
  },
  emptyState: {
    marginTop: 2,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 18,
    paddingHorizontal: 20,
  },
  emptyIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#e6f7f5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 6,
  },
  emptyText: {
    textAlign: "center",
    color: "#64748b",
    fontSize: 13,
    lineHeight: 18,
  },
});

export default styles;
