import { StyleSheet } from "react-native";
import reporteBaseStyles from "./ReporteClientesStyles";

// ATAMAINE: Lotes comparte el lenguaje visual compacto de los reportes nuevos,
// pero conserva estilos propios para sus dos autocompletados y el filtro de precio.
export const reporteLotesStyles = StyleSheet.create({
	...reporteBaseStyles,
	fieldLabel: {
		fontSize: 9,
		fontWeight: "900",
		color: "#334155",
		marginBottom: 6,
	},
	selectorWrap: {
		position: "relative",
		zIndex: 20,
		marginBottom: 8,
	},
	selectorWrapTop: {
		zIndex: 30,
	},
	selectorShell: {
		minHeight: 42,
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		paddingLeft: 11,
		paddingRight: 5,
		backgroundColor: "#f8fbff",
		borderRadius: 11,
		borderWidth: 1,
		borderColor: "#cfe0ef",
	},
	selectorShellFocused: {
		borderColor: "#14b8a6",
		backgroundColor: "#f4fffd",
	},
	selectorInput: {
		flex: 1,
		minWidth: 0,
		height: 40,
		paddingVertical: 0,
		fontSize: 10.5,
		fontWeight: "800",
		color: "#0f172a",
	},
	selectorIconButton: {
		width: 31,
		height: 31,
		borderRadius: 9,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#e8f8f5",
	},
	selectorClearButton: {
		width: 25,
		height: 31,
		alignItems: "center",
		justifyContent: "center",
	},
	optionsBox: {
		marginTop: 6,
		maxHeight: 238,
		backgroundColor: "#ffffff",
		borderWidth: 1,
		borderColor: "#bfe3df",
		borderRadius: 12,
		overflow: "hidden",
		elevation: 12,
		shadowColor: "#0f766e",
		shadowOffset: { width: 0, height: 9 },
		shadowOpacity: 0.18,
		shadowRadius: 14,
	},
	optionsHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 11,
		paddingVertical: 7,
		backgroundColor: "#ecfdf8",
		borderBottomWidth: 1,
		borderBottomColor: "#d7f1eb",
	},
	optionsHeaderText: {
		fontSize: 8,
		fontWeight: "900",
		color: "#0f766e",
		textTransform: "uppercase",
		letterSpacing: 0.35,
	},
	optionsScroll: {
		maxHeight: 200,
	},
	optionItem: {
		minHeight: 50,
		flexDirection: "row",
		alignItems: "center",
		gap: 9,
		paddingHorizontal: 10,
		paddingVertical: 8,
		borderBottomWidth: 1,
		borderBottomColor: "#edf3f7",
	},
	optionItemActive: {
		backgroundColor: "#effcf8",
	},
	optionIcon: {
		width: 30,
		height: 30,
		borderRadius: 9,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#e7f8f4",
	},
	optionContent: {
		flex: 1,
		minWidth: 0,
	},
	optionTitle: {
		fontSize: 10,
		lineHeight: 13,
		fontWeight: "900",
		color: "#102033",
	},
	optionMeta: {
		marginTop: 3,
		fontSize: 8,
		lineHeight: 10,
		fontWeight: "700",
		color: "#64748b",
	},
	optionEmpty: {
		alignItems: "center",
		paddingHorizontal: 14,
		paddingVertical: 17,
		gap: 5,
	},
	optionEmptyText: {
		fontSize: 9,
		fontWeight: "800",
		color: "#64748b",
		textAlign: "center",
	},
	priceShell: {
		marginBottom: 8,
	},
});

export default reporteLotesStyles;
